language: python
services:
    - elasticsearch
python:
    - "2.6"
    - "2.7"
env:
    - DJANGO=true
    - DJANGO=false

notifications:
  email: false

install:
    - virtualenv .
    - ./bin/pip install -r requirements-dev.txt
    - "[ $DJANGO = true ] && bin/pip install -r requirements-django.txt || echo"

script:
    - ./bin/python run_tests.py
